[settings]
experimental = true

[tools]
"ubi:MordechaiHadad/bob" = "latest"
node = "lts"
eza = "latest"
starship = "latest"
ripgrep = "latest"
zellij = "latest"
lazygit = "latest"
bat-extras = "latest"
bat = "latest"
difftastic = "latest"
fzf = "latest"
zoxide = "latest"
usage = "latest"

